### ISSUE TITLE
Webpay Produccion

### ISSUE THREAD

**Issue by manuelabarca** [rgcl/webpay-nodejs#12]
No he podido ponerlo en marcha desde productivo, me dice error null key 263 y tengo todos los certificados bien, alguna ayuda o solución ?

**Comment by eliseolara** [comment]
Hola amigo, pudiste solucionarlo?

**Comment by manuelabarca** [comment]
No estaba cambiando esto a produccion de manera correcta

env: WebPay.ENV.INTEGRACION

Dejo mi repositorio con proyecto base
https://github.com/manuelabarca/webpay-angular

**Comment by eliseolara** [comment]
Gracias!
pero no entiendo mucho de programación! Estoy tratando de validar Webpay Plus, solo con tutoriales!

Estoy a prueba y error... en algun momento me funcionará, pero cual será el problema ¿Ese Será Otro Dilema?

**Comment by tebantebanteban** [comment]
Hola @eliseolara  , cuenta un poco más que problema tienes, en que lo estás desarrollando a ver si podemos ayudarte en algo.

**Comment by eliseolara** [comment]
Hola @tebantebanteban gracias por tu intensión de ayudarme!

Te cuento que hice la integración de Webpay con PHP seguido del tutorial Transbank WebServices SDK [https://github.com/freshworkstudio/transbank-web-services/blob/master/readme.md#transbank-webservices-sdk](url) y con este pude pasar el proceso de integración y validación de Transbank, pero el problema esta al momento de cambiar de **integracion** a **produccion**

Al momento de presionar el boton pagar ejecuto el archivo tbk-pagar.php

**use Freshwork\Transbank\CertificationBagFactory;
use Freshwork\Transbank\TransbankServiceFactory;
use Freshwork\Transbank\RedirectorHelper;
include 'vendor/autoload.php';
$bag = CertificationBagFactory::integrationWebpayNormal();
$webpay = TransbankServiceFactory::normal($bag);
$webpay->addTransactionDetail($TRA_amount, $TRA_buyOrder);
$response = $webpay->initTransaction('http://evolucionwifi.cl/webpay/response.php', 'http://evolucionwifi.cl/webpay/tbk-finish.php');
echo RedirectorHelper::redirectHTML($response->url, $response->token);**

Según lo que leía en el tutorial solo debo de invocar la clase _CertificationBagFactory::production();_, pero no se donde incluir el certificado Publico de Transbank

**Comment by tebantebanteban** [comment]
@eliseolara  Pero si en certificación funciona bien y lograste obtener la aprobación de Transbank es porque tu flujo está bien.

- Cambiaste los certificados?, esto significa que debes cambiar los certificados del código de comercio que estás integrando (.cert y .key) y además, debes cambiar el certificado de transbank al de producción.

* Si intentas conectar usando tus certificados de producción con el certificado transbank de certificación te saldrá un error y viceversa también.
* El certificado público de transbank de producción es igual para todos pero te lo envían de todas formas en el último correo de aprobación de certificación transbank.

en relación a lo que señalas:

> Según lo que leía en el tutorial solo debo de invocar la clase CertificationBagFactory::production();, pero no se donde incluir el certificado Publico de Transbank

Ojo con esta parte del tutorial de Freshwork Transbank donde se señala como manejar la carpeta de certificados:

<img width="935" alt="Captura de pantalla 2019-04-15 a la(s) 13 45 30" src="https://user-images.githubusercontent.com/31634150/56153737-dbd4f800-5f84-11e9-9706-12026ea76ed0.png">

Cuéntame como te va!

**Comment by eliseolara** [comment]
una vez mas gracias por tu ayuda! Lo primero, volvi todo a la etapa de integración y modifique solo la linea

CertificationBagFactory::integrationWebpayNormal(); por
CertificationBagFactory::production('ruta absoluta') y ahora estoy con el error del inicio de todo esto 



estoy haciendo una prueba y te cuento como me va!

**Comment by eliseolara** [comment]
Ahora volvi a este error!

Fatal error: Uncaught SoapFault exception: [soap:Server]  in /home/evolucionwifi/public_html/webpay/vendor/freshwork/transbank/src/TransbankWebService.php:136 Stack trace: #0 /home/evolucionwifi/public_html/webpay/vendor/freshwork/transbank/src/WebpayStandard/WebpayStandardWebService.php(59): Freshwork\Transbank\TransbankWebService->callSoapMethod('initTransaction', Object(Freshwork\Transbank\WebpayStandard\InitTransaction)) #1 /home/evolucionwifi/public_html/webpay/vendor/freshwork/transbank/src/WebpayWebService.php(160): Freshwork\Transbank\WebpayStandard\WebpayStandardWebService->initTransaction(Object(Freshwork\Transbank\WebpayStandard\InitTransactionInput)) #2 /home/evolucionwifi/public_html/webpay/tbk-pagar.php(21): Freshwork\Transbank\WebpayWebService->initTransaction('http://evolucio...', 'http://evolucio...') #3 {main} thrown in /home/evolucionwifi/public_html/webpay/vendor/freshwork/transbank/src/TransbankWebService.php on line 136

**Comment by eliseolara** [comment]
@tebantebanteban te cuento!!!

El certificado que enviaba a TBK aun no esta ingresado en los servidores, por eso nunca iba a validar!

Cuando tenga novedad te aviso, muchas gracias por todo tu tiempo y ayuda!

**Comment by gdespirito** [comment]
Hola! Soy el autor del paquete de PHP que hablan. ¿Necesitan ayuda con algo?

**Comment by MauricioDonoso** [comment]
@manuelabarca el certificado de webpaykey como lo generas? y los otros 2 certificados los generaste con el codigo de comercio de produccion?
